# Generated by Django 4.2.10 on 2024-02-25 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nbhood_watch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='submission',
            name='submission_location',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submission_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Submitted'),
        ),
        migrations.AddField(
            model_name='submission',
            name='submission_user',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='nbhood_watch.user'),
        ),
    ]
