# Generated by Django 4.2.10 on 2024-03-11 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbhood_watch', '0006_alter_submission_submission_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='submission_location',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='submission_text',
        ),
        migrations.AddField(
            model_name='submission',
            name='submission_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
