# Generated by Django 4.2.10 on 2024-03-14 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nbhood_watch', '0009_user_user_name_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='username',
        ),
    ]
