# Generated by Django 4.2.10 on 2024-03-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbhood_watch', '0010_rename_user_name_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, default='Anon', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, default='Anon', max_length=100, null=True),
        ),
    ]
