# Generated by Django 4.2.10 on 2024-03-17 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nbhood_watch', '0012_user_last_login'),
        ('nbhood_watch', '0013_submission_submission_status'),
    ]

    operations = [
    ]
