# Generated by Django 4.2.10 on 2024-03-17 15:41

from django.db import migrations, models
import django.db.models.deletion
import nbhood_watch.models


class Migration(migrations.Migration):

    dependencies = [
        ('nbhood_watch', '0014_merge_20240317_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submission_file',
            field=models.FileField(blank=True, null=True, upload_to=nbhood_watch.models.submission_file_path),
        ),
        migrations.CreateModel(
            name='SubmissionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=nbhood_watch.models.submission_file_path)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='nbhood_watch.submission')),
            ],
        ),
    ]
