# Generated by Django 4.2.10 on 2024-03-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbhood_watch', '0015_alter_submission_submission_file_submissionfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='submission_category',
            field=models.CharField(choices=[('Safety Concerns', 'Safety Concerns'), ('Environmental Issues', 'Environmental Issues'), ('Public Disturbances', 'Public Disturbances'), ('Illegal Activities', 'Illegal Activities'), ('Maintenance Issues', 'Maintenance Issues'), ('Lost/Found Items', 'Lost/Found Items'), ('Other', 'Other')], default='Safety Concerns', max_length=20),
        ),
    ]
