# Generated by Django 4.2.10 on 2024-03-22 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbhood_watch', '0015_alter_submission_submission_file_submissionfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='submission_desc',
            new_name='submission_text',
        ),
        migrations.AddField(
            model_name='submission',
            name='submission_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='submission_summary',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
