# Generated by Django 4.2.10 on 2024-03-24 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nbhood_watch', '0016_rename_submission_desc_submission_submission_text_and_more'),
        ('nbhood_watch', '0016_submission_submission_category'),
    ]

    operations = [
    ]
