# Generated by Django 4.2.10 on 2024-03-24 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nbhood_watch', '0017_merge_20240324_1614'),
        ('nbhood_watch', '0017_merge_20240324_1615'),
    ]

    operations = [
    ]
