# Generated by Django 4.2.10 on 2024-03-24 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbhood_watch', '0019_rename_submission_summary_submission_submission_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='submission_verification',
            field=models.CharField(choices=[('Verified', 'Verified'), ('Unverified', 'Unverified')], default='Unverified', max_length=20),
        ),
    ]
