# Generated by Django 4.2.10 on 2024-03-24 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbhood_watch', '0020_submission_submission_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='submission_admin_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
