# Generated by Django 4.2.10 on 2024-03-25 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbhood_watch', '0021_submission_submission_admin_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submission_verification',
            field=models.CharField(choices=[('Verified', 'Verified'), ('Unverified', 'Unverified'), ('False Information', 'False Information')], default='Unverified', max_length=20),
        ),
    ]
