# Generated by Django 4.2.10 on 2024-04-07 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nbhood_watch', '0022_alter_submission_submission_verification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='submission_desc',
            new_name='submission_description',
        ),
    ]
