# Generated by Django 4.2.10 on 2024-04-10 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbhood_watch', '0023_rename_submission_desc_submission_submission_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
