# Generated by Django 4.2.10 on 2024-04-28 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbhood_watch', '0024_submission_latitude_submission_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submission_admin_notes',
            field=models.TextField(blank=True, default='N/A', null=True),
        ),
    ]
