# Generated by Django 4.2.10 on 2024-04-28 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbhood_watch', '0025_alter_submission_submission_admin_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submission_description',
            field=models.TextField(blank=True, help_text='*required', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submission_title',
            field=models.TextField(blank=True, help_text='*required', max_length=300, null=True),
        ),
    ]
